title: "[Idea]: "
labels:
  - discussion
  - ideas
body: |
  ## 💡 Your Idea

  <!-- Share your idea for improving Claudius Skills -->

  ## Problem or Opportunity

  <!-- What problem does this address, or what opportunity does it create? -->

  ## Benefits

  <!-- How would this benefit users of Claudius Skills? -->

  ## Potential Challenges

  <!-- Any challenges or considerations to be aware of? -->

  ## Additional Context

  <!-- Any additional information, examples, or context -->
