title: "[Show & Tell]: "
labels:
  - discussion
  - showcase
body: |
  ## 🎨 What Did You Build?

  <!-- Tell us about your project using Claudius Skills -->

  ## Which Kits/Skills Did You Use?

  <!-- Which kits, skills, commands, or other components did you use? -->

  ## Screenshots or Demo

  <!-- Share screenshots, GIFs, or links to your project -->

  ## What You Learned

  <!-- What did you learn while building this? -->

  ## Tips for Others

  <!-- Any tips or advice for others building similar projects? -->
