name: Feature Request
description: Suggest a new skill, command, hook, or other feature
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Skill
        - New Slash Command
        - New Hook
        - New Subagent
        - New Framework Rule
        - New Kit/Collection
        - Documentation Improvement
        - Other Enhancement
    validations:
      required: true

  - type: dropdown
    id: skill-level
    attributes:
      label: Target Skill Level
      description: Which kit/level should this feature target?
      options:
        - Starter Kit (Beginner)
        - Intermediate Kit
        - Advanced Kit (Enterprise)
        - Productivity Skills
        - Competitive AI Frameworks
        - Eliza OS Kit
        - Multiple Levels
        - Not Applicable
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a user, I need to... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would this feature work?
      placeholder: |
        I propose a skill/command/hook that...

        Example usage:
        ```bash
        /new-command arg1 arg2
        ```

        Expected behavior:
        - ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: I also considered... but...
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of when this would be useful
      placeholder: |
        1. When building a React app, I would use this to...
        2. When deploying to production, this would help...
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Would you be willing to contribute this feature?
      description: Would you like to help implement this?
      options:
        - "Yes, I can implement this"
        - "Yes, with guidance"
        - "No, but I can test it"
        - "No"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information or context
      placeholder: Add any other context, mockups, or examples
    validations:
      required: false
